name: Update survey health files
on:
  schedule:
    - cron:  '30 10 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Test with tox
      run: |
        pip install tox
        tox -e health_update
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v2.7.0
      with:
        token: ${{ secrets.SURVEY_HEALTH }}
        commit_message: Updating survey health files
        title: Updating survey health files
        author: Survey Health Cron Job <drawdownbot@decarbon.earth>
        team-reviewers: owners, maintainers
